<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <Authors>Nozomu-san</Authors>
    <AssemblyVersion>16.08.2026.0</AssemblyVersion>
    <FileVersion>16.08.2026.0</FileVersion>
    <AssemblyTitle>Generic JSON Configuration Standard</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StandardDataPipeline\StandardDataPipeline.csproj" />
  </ItemGroup>

</Project>
